<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKAUu1e8\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKAUu1e8/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKAUu1e8.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKAUu1e8\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerKAUu1e8\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'KAUu1e8',
    'container.build_id' => '9a4451bc',
    'container.build_time' => 1517321335,
));
